### ISSUE TITLE
3-arg min_by and max_by Presto functions uses too much memory

### ISSUE THREAD

**Issue by mbasmanova** [facebookincubator/velox#9254] opened 2024-03-26 13:44 UTC
### Bug description

PR https://github.com/facebookincubator/velox/pull/8566 introduced a regression in memory usage of 3-arg min_by and max_by aggregates: https://github.com/facebookincubator/velox/commit/080b7857139ca647e90a5cee81344f920a1be84d#r140246346

min_by and max_by maintain top N value pairs in memory. Before the change, when replacing on the top pairs, these functions used to release memory allocated for the removed pair. After the change, they stopped releasing the memory and keep it allocated until all data is finished processing. 

min_by: Peak memory: 131.50KB

```
] [ROW ROW<a0:ARRAY<ARRAY<BIGINT>>>: 1 elements, no nulls]
] 0: {2 elements starting at 0 {100 elements starting at 0 {0, 1, 2, 3, 4, ...}, 100 elements starting at 100 {100, 101, 102, 103, 104, ...}}}

] -- Aggregation[SINGLE a0 := min_by(ROW["c0"],ROW["c1"],2)] -> a0:ARRAY<ARRAY<BIGINT>>
   Output: 1 rows (2.03KB, 1 batches), Cpu time: 1.84ms, Blocked wall time: 0ns, Peak memory: 131.50KB, Memory allocations: 11, Threads: 1
  -- Values[1000 rows in 1 vectors] -> c0:ARRAY<BIGINT>, c1:BIGINT
     Input: 0 rows (0B, 0 batches), Output: 1000 rows (1.02MB, 1 batches), Cpu time: 48.57us, Blocked wall time: 0ns, Peak memory: 0B, Memory allocations: 0, Threads: 1
```

max_by: Peak memory: 2.32MB

```
] [ROW ROW<a0:ARRAY<ARRAY<BIGINT>>>: 1 elements, no nulls]
] 0: {2 elements starting at 0 {100 elements starting at 0 {99900, 99901, 99902, 99903, 99904, ...}, 100 elements starting at 100 {99800, 99801, 99802, 99803, 99804, ...}}}

] -- Aggregation[SINGLE a0 := max_by(ROW["c0"],ROW["c1"],2)] -> a0:ARRAY<ARRAY<BIGINT>>
   Output: 1 rows (2.03KB, 1 batches), Cpu time: 59.53ms, Blocked wall time: 0ns, Peak memory: 2.32MB, Memory allocations: 15, Threads: 1
  -- Values[1000 rows in 1 vectors] -> c0:ARRAY<BIGINT>, c1:BIGINT
     Input: 0 rows (0B, 0 batches), Output: 1000 rows (1.02MB, 1 batches), Cpu time: 52.19us, Blocked wall time: 0ns, Peak memory: 0B, Memory allocations: 0, Threads: 1    
```

Simple code to illustrate the issue:

```
TEST_F(MinMaxByNTest, xxx) {
  auto data = makeRowVector({
      // Each array has 10 elements.
      makeArrayVector<int64_t>(
          1'000, [](auto row) { return 100; }, [](auto row) { return row; }),
      makeFlatVector<int64_t>(1'000, [](auto row) { return row; }),
  });

  core::PlanNodeId aggId;
  auto plan = PlanBuilder()
                  .values({data})
                  .singleAggregation({}, {"min_by(c0, c1, 2)"})
                  .capturePlanNodeId(aggId)
                  .planNode();

  std::shared_ptr<exec::Task> task;
  auto results = AssertQueryBuilder(plan).copyResults(pool(), task);

  LOG(ERROR) << results->toString();
  LOG(ERROR) << results->toString(0, 10);

  LOG(ERROR) << exec::printPlanWithStats(*plan, task->taskStats());
}
```

CC: @bikramSingh91 @kagamiori @f0rest9999 @kgpai 

### System information

n/a

**Comment by mbasmanova** [comment] 2024-03-26 13:45
CC: @xiaoxmeng

**Comment by bikramSingh91** [comment] 2024-03-26 16:35
For context: @kagamiori correct me if i am wrong, the issue fixed in https://github.com/facebookincubator/velox/pull/8566 was that extractValues would release the top pairs so that they could not be used to generate output for other rows in the same window. The fix explicitly ensured that they would not be released. I remember Wei mentioned that most of the agg functions don’t release the top pairs which is why they work fine in window aggregation.

I wonder whether its possible to explicitly clear the accumulator when values are extracted and its not a window aggregation. That might also reduce mem usage for other agg functions that already don’t release the top pairs.

**Comment by kagamiori** [comment] 2024-03-26 17:36
I think the problem is that when we pop_heap an pair from the heap, we didn't free the memory allocated with that pair. Let me verify if this is the issue with the unit test and send a fix.

**Closed** 2024-04-02 18:40 UTC
Labels: bug, performance, triage
