### ISSUE TITLE
Add documentation for HashTable

### ISSUE THREAD

**Issue by baibaichen** [facebookincubator/velox#1555] opened 2022-05-06 15:40 UTC
It would be great to add documentation for HashTable on the [Join](https://facebookincubator.github.io/velox/develop/joins.html) page since it is very important data structure for join and aggregation.

Design consideration：

1. Why convert  to Row in case of join and aggregation and how does it affect performance? Actually it surprised me that there are many random read in hash probe. 
2. What's the difference between join and aggregation.
3. How SIMD is used in vector HASH Table?

Implemenation details:

1. How is hash conflict detected?
2. Which probe algorithm is used？

References:
- https://duckdb.org/2022/03/07/aggregate-hashtable.html
- https://engineering.fb.com/2019/04/25/developer-tools/f14/

**Comment by mbasmanova** [comment] 2022-05-06 15:43
CC: @oerling

**Comment by baibaichen** [comment] 2022-05-19 03:29
> It will take me some time to write the documentation article on this topic. In the meantime, the latest Photon paper from Databricks gives some context. I view Velox as an open source version of Photon and the paper's content applies mostly as-is.
> 
> https://www-cs.stanford.edu/~matei/papers/2022/sigmod_photon.pdf
> 
> In particular, 3.4 Row vs. Column-Oriented Execution section has some info relevant to this issue:
> 
> ```
> In practice, Photon does pivot columns to rows in certain scenarios. For example, we generally buffer data in data structures such
> as hash tables as rows, since storing data as columns here requires
> expensive random accesses when performing operations such as
> key comparisons during hash table probing.
> ```

IIUC,  We only need buffer join-keys in probing case, however non-join key columns are also converted to row, that's why i can't understand.

**Comment by mbasmanova** [comment] 2022-12-06 15:46
@baibaichen We didn't have a chance to work on this documentation yet.

**Comment by ViggoC** [comment] 2023-03-21 03:36
I also look forward to this document very much.

**Comment by sanumandla** [comment] 2023-12-04 18:25
[Velox Hash Tables - Orri Erling.pdf](https://github.com/facebookincubator/velox/files/13549964/Velox.Hash.Tables.-.Orri.Erling.pdf)

Uploading the recent talk from Orri Erling about Velox Hash Tables

**Comment by mbasmanova** [comment] 2023-12-07 16:33
Velox, like F14, is bucketed tagged table.

- slot = 7 bytes: 1 byte tag + 6 bytes pointer.

- bucket = 16 slots + 16 bytes padding = 2 * 64 bytes = 2 cache lines.

- table = power of 2 buckets.

```
/// Extracts a 7 bit tag from a hash number. The high bit is always set.
static uint8_t hashTag(uint64_t hash) {
   return static_cast<uint8_t>(hash >> 32) | 0x80;
}
```

**Comment by mbasmanova** [comment] 2023-12-22 11:48
### Layout

HashTable is implemented as an array of buckets. It is a linear data structure. Each bucket uses 128 bytes (2 * 64 = 2 cache lines) and contains 16 slots. Each HashTable entry occupies one slot. HashTable’s capacity is the total number of slots: total number of buckets * 16. HashTable’s capacity is always a power of 2. 

Each bucket contains 16 slots. Each slot consists of 2 pieces: a tag (7 bits) and a pointer (6 bytes). There are a total of 16 tags and 16 pointers in a bucket. These are stored tags first, followed by pointers. Each tag occupies 1 byte (only 7 bits are used). 16 tags occupy 16 bytes. Each pointer occupies 6 bytes. 16 pointers occupy 48 bytes. There are 16 bytes left unused at the end of the bucket. These are referred to as padding. 

<img width="888" alt="ht_layout" src="https://github.com/facebookincubator/velox/assets/27965151/3b3f268f-9353-44d6-b3fa-1fd32e6c8ce1">

A hash table is never full. There are always some empty slots. Velox allows HashTable to fill up to ⅞ of capacity before resizing. On resize HashTable’s capacity doubles.

Individual buckets may be completely empty, partially filled or full. Buckets are filled left to right. If a bucket is partially full, then first N tags and N pointers are filled and the rest are free (N < 16).

### Inserting an entry

To insert a new entry we need to figure out which slot to put it in. A slot is identified by bucket and offset within the bucket. First, we compute a hash of the entry. Then, we compute a tag and a bucket number from the hash.

We use 7 bits of the hash for the tag: bits 32-38 inclusive. We use N bits of the hash for the bucket starting from bit 8.

Given hash number 

01011011 11001010 01111100 0**1101001** 10110111 1**0010100 11111000 1**1001110

We compute the tag as 1**1101001** and bucket offset as 1,374,336 (00000000 00000000 00000000 00000000 00000000 0**0010100 11111000 1**0000000). Bucket offset is the number of bytes from the start of the hash table.

	Bucket offset = bucket number * 128
	Bucket number = bucket offset / 128

We use a bucket offset to get to the bucket. Here we have a few possibilities. The bucket might be empty. 

<img width="884" alt="empty_bucket" src="https://github.com/facebookincubator/velox/assets/27965151/b1ea99ac-a4ba-4e22-a409-fd29ce6295c0">

In this case, we simply insert our entry into the first slot of the bucket. We store only the tag (7 bits of the hash value) in the hash table. The hash number itself is not stored. The pointer refers to memory outside of the HashTable where the complete value is stored. This is usually a row in a RowContainer. The HashTable can be viewed as an index on top of a RowContainer that helps locate records with matching keys faster. HashTable itself doesn’t store data or keys.

<img width="876" alt="insert_1st" src="https://github.com/facebookincubator/velox/assets/27965151/5f03cd1c-5e24-4626-b560-42f0aff8f6f1">

Another possibility is a bucket partially filled (for example, has one slot occupied like above). In this case there is a possibility that the new entry is a duplicate of the one already stored. Hence, we compare the tag of the new entry with tags stored in the bucket. If none match, this entry is not a duplicate, so we store it in the next available slot in the bucket.

<img width="883" alt="Screenshot 2023-12-22 at 6 20 32 AM" src="https://github.com/facebookincubator/velox/assets/27965151/c2081c7c-2b0e-4bbb-be62-d8eb42d4159d">

However, if one or more existing tags match the tag of the new entry, we follow the pointers to compare the keys to determine whether there is a match or not. If not, match, we insert a new entry. Otherwise, we drop it.

A final possibility is that the bucket is full.

<img width="879" alt="full_bucket" src="https://github.com/facebookincubator/velox/assets/27965151/1f7d77d3-95d3-4646-bcd6-4a04f0e77d29">

First, we need to check if the new entry is a duplicate of one of the 16 entries stored in the bucket. We compare tags and if necessary following pointers to compare the keys. If there is a match, we drop the entry and we are done. If there is no match, we go to the next bucket and repeat the process. In rare cases, we may end up checking many buckets until we find a duplicate existing entry or an empty slot for the new entry. That’s why it is important to ensure that the Hash Table is never full and there are enough gaps in the form of empty slots.
Resizing
If HashTable fills up beyond ⅞ of capacity, it needs to be resized. Each resize doubles the capacity. We allocate a new HashTable and insert all existing entries using the “Inserting an entry” process. Since we know that all entries are unique, the “Inserting an entry” process can be simplified to eliminate the logic for checking whether a new entry is a duplicate of an existing one. Hence, to insert an entry, we compute a hash, extract tag and bucket number, go to the bucket and insert the entry if there is space. If the bucket is full, we proceed to the next bucket and continue until we find a bucket with an empty slot. We insert the new entry there.

### Use Cases

The main use cases for the HashTable are Join and Aggregation operators. 

HashBuild operator builds the HashTable to store unique values of the join keys found on the build side of the join. HashProbe operator looks up entries in the HashTable using join keys from the probe side. HashProbe operator does not insert new entries into the HashTable and never triggers a resize. The pointers in the HashTable refer to rows in a RowContainer that store individual rows for the build side of the join.

HashAggregation operator stores unique grouping keys in the HashTable. The pointers in the HashTable refer to rows in a RowContainer that store grouping keys along with accumulators of the aggregate functions.

CC: @duanmeng @xiaoxmeng @aditi-pandit

**Comment by aditi-pandit** [comment] 2023-12-22 17:31
Thanks Masha ! This is great !

@karteekmurthys @czentgr @majetideepak

**Comment by karteekmurthys** [comment] 2023-12-22 18:56
Thanks @mbasmanova for this documentation.

**Comment by czentgr** [comment] 2023-12-23 01:18
This is really nice! I took the liberty to convert the comment into its own documentation page and add some links to other pages.
PR https://github.com/facebookincubator/velox/pull/8167.

**Closed** 2024-01-03 22:04 UTC
Labels: documentation

**Comment by mbasmanova** [comment] 2024-01-04 00:56
Added documentation article: https://facebookincubator.github.io/velox/develop/hash-table.html
