### ISSUE TITLE
Possible race condition in facebook::velox::duckdb::InputStreamFileSystem

### ISSUE THREAD

**Issue by wesm** [facebookincubator/velox#967] opened 2022-02-01 23:59 UTC
I observed a possible race condition in `InputStreamSystem::CloseStream`:

```
E0201 17:43:45.266034 984237 Exceptions.h:68] .././velox/dwio/parquet/reader/duckdb/InputStreamFileSystem.h63CloseStreamit != lockedStreams->end()Unknown stream with ID 1014RUNTIMEINVALID_STATE
terminate called after throwing an instance of 'facebook::velox::VeloxRuntimeError'
  what():  Exception: VeloxRuntimeError
Error Source: RUNTIME
Error Code: INVALID_STATE
Reason: Unknown stream with ID 1014
Retriable: False
Expression: it != lockedStreams->end()
Function: CloseStream
File: .././velox/dwio/parquet/reader/duckdb/InputStreamFileSystem.h
Line: 63
Stack trace:
# 0  
# 1  
# 2  
# 3  
# 4  
# 5  
# 6  
# 7  
# 8  
# 9  
# 10 
# 11 
# 12 
# 13 
# 14 
# 15 
# 16 
# 17 
# 18 
# 19 
# 20 
# 21 
# 22 

--Type <RET> for more, q to quit, c to continue without paging--

Thread 1146 "CPUThreadPool3" received signal SIGABRT, Aborted.
[Switching to Thread 0x7fff6d7fa700 (LWP 984237)]
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff743d859 in __GI_abort () at abort.c:79
#2  0x00007ffff7812911 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff781e38c in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff781d369 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff781dd21 in __gxx_personality_v0 () from /lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007ffff761abef in ?? () from /lib/x86_64-linux-gnu/libgcc_s.so.1
#7  0x00007ffff761b5aa in _Unwind_Resume () from /lib/x86_64-linux-gnu/libgcc_s.so.1
#8  0x00005555570c097d in facebook::velox::duckdb::InputStreamFileSystem::CloseStream(int) ()
#9  0x00005555570bfd2f in facebook::velox::duckdb::InputStreamFileHandle::~InputStreamFileHandle() ()
#10 0x0000555557f774e3 in duckdb::ParquetReader::~ParquetReader() ()
#11 0x00005555568490fa in facebook::velox::parquet::ParquetReader::~ParquetReader() ()
#12 0x000055555680a66e in facebook::velox::connector::hive::HiveDataSource::next(unsigned long) ()
#13 0x00005555568e8fcf in facebook::velox::exec::TableScan::getOutput() ()
#14 0x0000555556879445 in facebook::velox::exec::Driver::runInternal(std::shared_ptr<facebook::velox::exec::Driver>&, std::shared_ptr<facebook::velox::exec::BlockingState>*) ()
```

If a thread is waiting on `wlock()` while another thread is holding the lock and closing the stream for the same id, then this would occur.  Don't have an easy minimal reproducer

**Comment by majetideepak** [comment] 2022-02-02 00:16
@wesm I have a fix for this coming up here https://github.com/facebookincubator/velox/pull/923
The change for this particular fix is in this commit https://github.com/facebookincubator/velox/pull/923/commits/0122b20b0378ea3c3c77673661885f3c7285e551
Can you try this fix? Thanks.

**Comment by wesm** [comment] 2022-02-02 01:20
That fix seems to work for me

**Comment by 9prady9** [comment] 2022-02-02 12:57
@majetideepak @wesm I am still seeing the problem. I don't think it is a residue effect of past builds, because I did clean build and that still has the issue. I am trying to create a Test in existing velox tests to help share a reproducible.

**Comment by 9prady9** [comment] 2022-02-10 09:10
The file IO stream issue reported in this issue originally seems to have been resolved by this https://github.com/facebookincubator/velox/commit/d12a1f94272492a6d10eca9ecf237d0ea0f2c5db Once we rebased from latest changes last week, the repetitive IO stream disappeared.

So, I think this particular issue can be closed.

**Closed** 2022-02-12 03:10 UTC
