### ISSUE TITLE
A failure found during StringColumnReader dedictionarizing process

### ISSUE THREAD

**Issue by rui-mo** [facebookincubator/velox#2808] opened 2022-10-11 06:36 UTC
Hi,
We found a failure in `StringColumnReader::dedictionarize` seemed to be  caused by the access to nullptr.

At below place ([StringColumnReader](https://github.com/facebookincubator/velox/blob/main/velox/dwio/parquet/reader/StringColumnReader.cpp#L155)), the `rawValues_` is set to be nullptr.

```
rawValues_ = nullptr;
```

But it is then accessed in `addStringValue` function at [SelectiveColumnReader](https://github.com/facebookincubator/velox/blob/main/velox/dwio/common/SelectiveColumnReader.cpp#L299).

```
void SelectiveColumnReader::addStringValue(folly::StringPiece value) {
  auto copy = copyStringValue(value);
  reinterpret_cast<StringView*>(rawValues_)[numValues_++] =
      StringView(copy, value.size());
}
```

@yingsu00 @oerling Would you like to provide us with some details on the logics here?

**Comment by rui-mo** [comment] 2022-10-11 06:37
cc @FelixYBW

**Comment by mbasmanova** [comment] 2022-10-11 13:34
@oerling Orri, would you check this out?

**Comment by mbasmanova** [comment] 2022-10-11 13:34
CC: @Yuhta

**Comment by oerling** [comment] 2022-10-12 21:45
We have not gotten the test data generator to make mixed dictionary/plain columns of strings. Will try harder. This should be readily fixable.

**Comment by rui-mo** [comment] 2022-10-13 03:23
> @rui-mo Rui, do you have a stack trace and a repro to share?

@mbasmanova Masha, below is the stack trace we got.

```
C  [libvelox.so+0xc6d9c86]  facebook::velox::dwio::common::SelectiveColumnReader::addStringValue(folly::Range<char const*>)+0xa4
C  [libvelox.so+0xb0ac4d7]  facebook::velox::parquet::StringColumnReader::dedictionarize()+0x1d5
C  [libvelox.so+0xb115716]  facebook::velox::parquet::PageReader::rowsForPage(facebook::velox::dwio::common::SelectiveColumnReader&, bool, folly::Range<int const*>&, unsigned long const*&)+0x186
C  [libvelox.so+0xb0b05ea]  void facebook::velox::parquet::PageReader::readWithVisitor<facebook::velox::dwio::common::ColumnVisitor<folly::Range<char const*>, facebook::velox::common::AlwaysTrue, facebook::velox::dwio::common::ExtractToReader<facebook::velox::parquet::StringColumnReader>, true> >(facebook::velox::dwio::common::ColumnVisitor<folly::Range<char const*>, facebook::velox::common::AlwaysTrue, facebook::velox::dwio::common::ExtractToReader<facebook::velox::parquet::StringColumnReader>, true>&)+0xf2
C  [libvelox.so+0xb0af17a]  void facebook::velox::parquet::ParquetData::readWithVisitor<facebook::velox::dwio::common::ColumnVisitor<folly::Range<char const*>, facebook::velox::common::AlwaysTrue, facebook::velox::dwio::common::ExtractToReader<facebook::velox::parquet::StringColumnReader>, true> >(facebook::velox::dwio::common::ColumnVisitor<folly::Range<char const*>, facebook::velox::common::AlwaysTrue, facebook::velox::dwio::common::ExtractToReader<facebook::velox::parquet::StringColumnReader>, true>)+0x2c
C  [libvelox.so+0xb0ad575]  void facebook::velox::parquet::StringColumnReader::readHelper<facebook::velox::common::AlwaysTrue, true, facebook::velox::dwio::common::ExtractToReader<facebook::velox::parquet::StringColumnReader> >(facebook::velox::common::Filter*, folly::Range<int const*>, facebook::velox::dwio::common::ExtractToReader<facebook::velox::parquet::StringColumnReader>)+0x8b
C  [libvelox.so+0xb0ace27]  void facebook::velox::parquet::StringColumnReader::processFilter<true, facebook::velox::dwio::common::ExtractToReader<facebook::velox::parquet::StringColumnReader> >(facebook::velox::common::Filter*, folly::Range<int const*>, facebook::velox::dwio::common::ExtractToReader<facebook::velox::parquet::StringColumnReader>)+0x89
C  [libvelox.so+0xb0ac021]  facebook::velox::parquet::StringColumnReader::read(int, folly::Range<int const*>, unsigned long const*)+0x199
C  [libvelox.so+0xc6ed1e7]  facebook::velox::dwio::common::SelectiveStructColumnReader::read(int, folly::Range<int const*>, unsigned long const*)+0x3b5
C  [libvelox.so+0xc6ecd91]  facebook::velox::dwio::common::SelectiveStructColumnReader::next(unsigned long, std::shared_ptr<facebook::velox::BaseVector>&, unsigned long const*)+0x329
C  [libvelox.so+0xae3e8c9]  facebook::velox::parquet::ParquetRowReader::next(unsigned long, std::shared_ptr<facebook::velox::BaseVector>&)+0x15b
C  [libvelox.so+0xa5b1cb6]  facebook::velox::connector::hive::HiveDataSource::next(unsigned long, folly::SemiFuture<folly::Unit>&)+0x1a0
C  [libvelox.so+0x8311afb]  facebook::velox::exec::TableScan::getOutput()+0xa01

```

To reproduce this issue, as @oerling mentioned, if the data generator is not there, maybe we can reproduce this issue with a Velox TableScan test based on our test data, but we need to upload the data to somewhere you can download. How do you think so?

**Comment by mbasmanova** [comment] 2022-10-13 03:33
@rui-mo Would you share the test data over e-mail or via Slack?

**Comment by oerling** [comment] 2022-10-13 05:20
Fixed in 2829. This was a known case of lack of coverage, added now. You can try the fix, let us know..

 

Masha, would you review?

**Comment by rui-mo** [comment] 2022-10-13 10:18
@oerling Thank you for the fix! Made some initial tests on your PR and it solved the failure above. @mbasmanova I think our test data is not needed any more, right?

**Comment by mbasmanova** [comment] 2022-10-13 10:33
@rui-mo Happy to hear the issue is solved now. No need for test data.

**Closed** 2022-10-15 21:51 UTC
Labels: bug, io
