### ISSUE TITLE
Build fails on velox_memory_pool.cc

### ISSUE THREAD

**Issue by theosib-amazon** [facebookincubator/velox#3338] opened 2022-11-22 19:46 UTC
### Bug description

I'm trying to build Gluten, and it checks out the latest version of Velox. I'm getting a build error on velox_memory_pool.cc. Evidently this file is looking for MemoryPool when the class name has been changed to MemoryPoolBase. You can see the full compiler error output on this Gluten issue:

https://github.com/oap-project/gluten/issues/593

### System information

Latest version of Gluten. This is the build command for Gluten:

```
mvn clean package -Pbackends-velox -Pspark-3.2 -Pfull-scala-compiler -DskipTests -Dcheckstyle.skip -Dbuild_cpp=ON -Dbuild_velox_backend=ON -Dbuild_velox_from_source=ON -Dbuild_arrow=ON -Dvelox_enable_s3=ON
```

**Comment by assignUser** [comment] 2022-11-23 14:41
Velox does not have a stable API yet so any issues caused by that are generally up to the downstream project to handle. Which Gluten does, as you have received an answer in the linked issue I am closing this one.

**Closed by assignUser** 2022-11-23 14:41 UTC
Labels: build
