### ISSUE TITLE
Flaky test: ChecksumAggregateTest.reals

### ISSUE THREAD

**Issue by mbasmanova** [facebookincubator/velox#9292] opened 2024-03-28 17:50 UTC
### Bug description

https://github.com/facebookincubator/velox/actions/runs/8471059992/job/23210217320?pr=9291

```
[ RUN      ] ChecksumAggregateTest.reals
../../velox/functions/lib/aggregates/tests/utils/AggregationTestBase.cpp:807: Failure
Expected equality of these values:
  0
  spilledBytes(*task)
    Which is: 144
Google Test trace:
../../velox/functions/lib/aggregates/tests/utils/AggregationTestBase.cpp:766: Run partial + final with spilling
../../velox/functions/lib/aggregates/tests/utils/AggregationTestBase.cpp:108: VALUES ('AAAAAAAAAAA='),('bAFBcIKzvC4=')
[  FAILED  ] ChecksumAggregateTest.reals (524 ms)
```

CC: @xiaoxmeng 

### System information

n/a

**Comment by xiaoxmeng** [comment] 2024-04-10 21:14
Can't reproduce this offline so adding more log to help analyze in next occurrence: https://github.com/facebookincubator/velox/pull/9434

**Comment by xiaoxmeng** [comment] 2024-04-24 03:30
This should have been fixed by https://github.com/facebookincubator/velox/pull/9459

**Closed by xiaoxmeng** 2024-04-24 03:30 UTC
Labels: bug, triage, flaky-test
