### ISSUE TITLE
Parquet Writer Hotspot on memmove

### ISSUE THREAD

**Issue by yyang52** [facebookincubator/velox#5066] opened 2023-05-30 06:14 UTC
### Description

ETL (Velox w/ Spark/Gluten) is an essential part for data analytics which involves data files writing. Currently, Velox implements Parquet writer with Arrow writer, which supports various compression codecs. For ETL workload, ZSTD is a commonly-used compression method. And we had some benchmarks/tests to check the hotspot and see if some optimization potentials existed. 

Since Velox doesn't have a parquet writer benchmark, we implement a simple benchmark to write parquet files with TpchGen tables. While the workload profiling showed that the hotspots lay on `__memmove_avx_unaligned_erms` (> 50%), while `ZSTD_compress` only takes less than 10% time. While benchmarks on Arrow side gave a higher percentage of `ZSTD_compress` (more than 15% and > 80% when running `column_io_benchmark`)

**Velox workload:**
![image](https://github.com/facebookincubator/velox/assets/82208254/0ad1f862-31b2-425f-bac3-718d322febb0)
**Arrow workload:**
![image](https://github.com/facebookincubator/velox/assets/82208254/3aa6c4d7-a1e8-433c-9a60-914a516f596e)
![image](https://github.com/facebookincubator/velox/assets/82208254/e3bfd63f-8261-400b-920e-608104627bca)

Not sure if that's due to the different implementations of memory pool or I'm using some improper workloads. Do we happen to have some profiling data on parquet writer or is there any plan to optimize this part with SW/HW accelerators?

**Comment by yyang52** [comment] 2023-05-30 06:15
@oerling Any thoughts on that? Thanks!

**Comment by zhouyuan** [comment] 2023-05-30 07:32
CC: @JkSelf

**Comment by JkSelf** [comment] 2023-05-30 07:38
Can you try to see if this [PR#4854](https://github.com/facebookincubator/velox/pull/4854) can solve your problem? It seems that the performance degradation caused by frequent allocate and copy in the reallocate method of  DataBuffer.

**Comment by yyang52** [comment] 2023-05-30 08:04
> 

Thanks for providing that! Seems like we encounter a similar issue, as I also found `reservce` method took a lot of time. Will try this PR to see if the problem could be fixed.

**Comment by yyang52** [comment] 2023-05-31 05:30
> Can you try to see if this [PR#4854](https://github.com/facebookincubator/velox/pull/4854) can solve your problem? It seems that the performance degradation caused by frequent allocate and copy in the reallocate method of DataBuffer.

I have tried this PR and it does solve the problem! The hotspot becomes compression as `memmove` doesn't take that much time.

**Comment by majetideepak** [comment] 2024-07-19 21:30
Resolved with https://github.com/facebookincubator/velox/pull/4854

**Closed by majetideepak** 2024-07-19 21:30 UTC
Labels: enhancement
