### ISSUE TITLE
New vector sanity checks are firing in Prestissimo e2e tests

### ISSUE THREAD

**Issue by mbasmanova** [facebookincubator/velox#6059] opened 2023-08-09 13:27 UTC
### Bug description

5 tests are hitting the new check:

TestPrestoNativeJoinQueries>AbstractTestNativeJoinQueries.testLeftJoin
TestPrestoNativeJoinQueries>AbstractTestNativeJoinQueries.testAntiJoin
TestPrestoNativeJoinQueries>AbstractTestNativeJoinQueries.testSemiJoin
TestPrestoNativeTpchQueriesParquetUsingJSON>AbstractTestNativeTpchQueries.testTpchQ10
TestPrestoNativeTpchQueriesParquetUsingJSON>AbstractTestNativeTpchQueries.testTpchQ21

* VeloxRuntimeError: isValid String view at idx 1355 points outside of the string buffers

### System information

n/a

**Comment by pranjalssh** [comment] 2023-08-09 15:07
Why were these not caught in phabricator? Do we need to change any checks so we can make this visible at diff-time?

**Comment by mbasmanova** [comment] 2023-08-09 22:04
> Why were these not caught in phabricator? Do we need to change any checks so we can make this visible at diff-time?

Turns out, Phabricator runs this test using release build, but GitHub CI runs using debug build. The failing checks are debug-only checks.

**Comment by bikramSingh91** [comment] 2023-08-29 20:30
Update 1:
It seems like the Exchange right before the HashProbe is spitting out the vector with invalid data, I also confirmed that the source scan node that generates that data does not hit the validation check. Which means its either something in the Exchange operator or the sender operator (after scan) which is generating the incorrect vector.

Update 2:
I was finally able to trace it back to the PrestoSerializer. While generating stringBuffers, it tries to re-use an existing stringbuffer in the input ‘result’ vector. In this case, it finds a buffer of the required ‘capacity’, however, it did not update the ‘size’ of the buffer. This caused the newly appended string values to point outside of the buffer->size() but within buffer->capacity().

**Comment by wypb** [comment] 2023-09-21 06:12
Hi @bikramSingh91 @mbasmanova Has this problem been solved? I also encountered this problem when I submitted a PR today. You can see the log [here](https://app.circleci.com/pipelines/github/facebookincubator/velox/33957/workflows/0965a4ed-4697-4fcf-9a6c-766d49b409d8/jobs/221032)

**Comment by bikramSingh91** [comment] 2023-09-29 00:42
@wypb Yes this was resolved in #6337
The failure you are seeing is due to this issue: #6754

**Closed by bikramSingh91** 2023-09-29 00:42 UTC
Labels: bug
