### ISSUE TITLE
HashAggregate may produce output RowVector with unlimited batch size

### ISSUE THREAD

**Issue by marin-ma** [facebookincubator/velox#9540] opened 2024-04-19 02:10 UTC
### Bug description

In Gluten, the batch size in QueryConfig is set to 4096 by default, and is limited to 32768 during configuration checks.
```
 configs[velox::core::QueryConfig::kPreferredOutputBatchRows] = 
     std::to_string(veloxCfg_->get<uint32_t>(kSparkBatchSize, 4096)); 
 configs[velox::core::QueryConfig::kMaxOutputBatchRows] = 
     std::to_string(veloxCfg_->get<uint32_t>(kSparkBatchSize, 4096)); 
```
However, there are cases where the output from the Velox pipeline exceeds the configured batch size. One case was found in `HashAggregation::getOutput` method, which does not strictly control the number of rows outputted. Especially when newDistincts_ is true, the output size is determined by `lookup.newGroups.size()`, which can exceed `velox::core::QueryConfig::kMaxOutputBatchRows`
https://github.com/facebookincubator/velox/blob/84ae6bfd6f61775b9e20742cdc5bc73ecd0829c3/velox/exec/HashAggregation.cpp#L327-L345

If batch size is unlimited, it may more hurt Velox pipeline's performance. Velox is vectorized engine, basic policy is that one operator's output is used by following operator's input. So if batch size is too large it would lead to big cache miss and hurt performance. It's why we use 4K rows as default now.

### System information

N/A

**Comment by marin-ma** [comment] 2024-04-19 02:10
cc: @yangzhg @FelixYBW

**Comment by Yuhta** [comment] 2024-04-19 14:59
Large batch size won't hurt cache performance.  The limit is there for preventing OOM, in this case we already have the data in memory, flushing it with multiple batches does not help preventing OOM.

**Comment by FelixYBW** [comment] 2024-04-19 16:49
We tested 4K batch size has more than 10% perf gain compared to 32K batch size.

**Comment by Yuhta** [comment] 2024-04-19 17:06
In most of the cases it's auto prefetched into cache since it's mostly sequential.   If we want to squeeze the last bit out of TCPH, you can try to tweak `maxExtendedPartialAggregationMemoryUsage()` and see if the flush size can be reduced.  That will result in more flushes though I am not sure if the performance will be better.  Another way is to add a `Rebatch` operator to adjust batch sizes between operators, this way you can adjust them not just in HashAggregation but all the operators.

**Comment by FelixYBW** [comment] 2024-04-19 17:19
The problem is reported by Gluten shuffle actually, where we cache the input column data and fill into reducer's memory. The input column data is randomly accessed once for each reducer. It's scan multiple times.

Also in Velox design, since we have the maximal batch size control in config, all operator should follow this limit.

**Comment by Yuhta** [comment] 2024-04-19 18:07
I see, so the cache missing is actually coming outside Velox, and we never use Velox this way so never ran into too large a batch being a performance problem.  It should not be too hard to fix it just in HashAggregation, but still if the result is wrapped in dictionary, limiting the output row numbers from Velox is not enough to ensure the cache performance for your reducer.  The most reliable way would be adding a rebatch (and optionally flattening) step before passing data to reducer to make sure the whole vector fit in cache.

**Comment by FelixYBW** [comment] 2024-04-19 20:00
Thank you. we will submit a quick fix then.

**Comment by FelixYBW** [comment] 2024-04-25 17:33
We noted not only hash aggregate but also unnest may exceed the kMaxOutputBatchRows. Looks the config is for indication purpose not a hard limit. Let's close this issue until we noted it's a common performance regression issue from customers.

**Closed** 2024-04-26 17:24 UTC
Labels: bug, triage
