### ISSUE TITLE
Error: offsets[i] >= 1 (-8854437507224305640 vs. 1) k in frame bounds must be at least 1

### ISSUE THREAD

**Issue by spershin** [facebookincubator/velox#5490] opened 2023-06-30 22:50 UTC
### Bug description

Happens on a query with LAG() window function.
Note that the issue happens with DATE() type and not with STRING or INT types, although the problem with bad offset exists for all of them.

Exception happens in Window::updateKRowsFrameBounds()
We have two rows and
offsets[0] = {const long long} 7
offsets[1] = {const long long} -1095216660473
The memory is as following: 07 00 00 00   00 00 00 00   07 00 00 00   01 ff ff ff

For string and int types the memory is 07 00 00 00   00 00 00 00   07 00 00 00   01 00 00 00.
As you can see it is still a bad number, but it is not negative and does not trigger the check.
We should probably enhance the check to test for a reasonable numbers?

I've tested the RowContainer and it has all good data - I've recreated good vectors from each of two rows.
The bug must be in the Window classes - we read from the wrong place in the row container?
Unfortunately, I don't follow all the fields in the window classes to make sense of them and thus don't know what's wrong.

It is interesting that 1st and subsequent runs have different memory:
For DATE type it is 1st time:  07 00 00 00   00 00 00 00   07 00 00 00   01 00 00 00 // Does not trigger the >= 1 check!
For DATE type after 2nd+ time: 07 00 00 00   00 00 00 00   07 00 00 00   01 ff ff ff // Does trigger the >= 1 check!
For STRING type it is always:  07 00 00 00   00 00 00 00   07 00 00 00   01 00 00 00 // Does not trigger the >= 1 check!

cc @aditi-pandit 

A bit unrelated, but btw, why do we need row containers? Just for sorting?
We could do sorting "outside" or row vector and just reshuffle the indices.
That way, I think, we won't need to copy data to and from row containers?

### System information

Velox System Info v0.0.2
Commit: f37ecccca34d96c0e931fc90341080124f38d6dc
CMake Version: 3.26.4
System: Darwin-22.5.0
Arch: x86_64
C++ Compiler: /Library/Developer/CommandLineTools/usr/bin/c++
C++ Compiler Version: 12.0.0.12000032
C Compiler: /Library/Developer/CommandLineTools/usr/bin/cc
C Compiler Version: 12.0.0.12000032
CMake Prefix Path: /Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/usr;/usr/local;/usr;/;/usr/local/Cellar/cmake/3.26.4;/usr/local;/usr/X11R6;/usr/pkg;/opt;/sw;/opt/local
  

### Relevant logs

```bash
Query to reproduce with a coordinator + single (or many) worker.
Can possibly be recreated in a unit test too, I suppose, but I haven't got around doing it.


SELECT 
  b.ds, 
  LAG(spend_this_period, 7) OVER (
    ORDER BY 
      b.ds ROWS BETWEEN 7 PRECEDING 
      AND CURRENT ROW
  ) AS spend_prev_period 
FROM 
  (
    SELECT 
      * 
    FROM 
      (
        VALUES 
          (
            DATE('2023-06-21'), 
            95317.96574958303
          )
      ) AS a (ds, spend_this_period)
  ) a 
  RIGHT JOIN (
    SELECT 
      * 
    FROM 
      (
        VALUES 
          (
            DATE('2023-06-21')
          ), 
          (
            DATE('2023-06-22')
          )
      ) AS r(ds)
  ) b ON b.ds = a.ds;


The input data for the Window operator are two rows (separate):

I20230630 15:27:51.838583 1912369 Window.cpp:158] ---- Input: [ROW ROW<field_0:DOUBLE,expr_24:BIGINT,field_14:DATE,expr_26:INTEGER>: 1 elements, no nulls]
I20230630 15:27:51.838706 1912369 Window.cpp:160] ---- Input[0]: 0: 95317.96574958303
I20230630 15:27:51.838762 1912369 Window.cpp:160] ---- Input[1]: 0: 7
I20230630 15:27:51.838785 1912369 Window.cpp:160] ---- Input[2]: 0: 2023-06-21
I20230630 15:27:51.838814 1912369 Window.cpp:160] ---- Input[3]: 0: 7

I20230630 15:28:23.006311 1912327 Window.cpp:158] ---- Input: [ROW ROW<field_0:DOUBLE,expr_24:BIGINT,field_14:DATE,expr_26:INTEGER>: 1 elements, no nulls]
I20230630 15:28:23.006526 1912327 Window.cpp:160] ---- Input[0]: 0: null
I20230630 15:28:23.006579 1912327 Window.cpp:160] ---- Input[1]: 0: 7
I20230630 15:28:23.006620 1912327 Window.cpp:160] ---- Input[2]: 0: 2023-06-22
I20230630 15:28:23.006667 1912327 Window.cpp:160] ---- Input[3]: 0: 7
```

**Comment by mbasmanova** [comment] 2023-07-03 12:50
CC: @aditi-pandit

**Comment by aditi-pandit** [comment] 2023-07-03 17:42
@spershin : Its weird that logic is even triggered since for frame (BETWEEN 7 PRECEDING AND CURRENT ROW) --> 7 PRECEDING is a constant offset so there isn't really an offsets column to read. So the code is definitely reading from somewhere unintended to read.

Its more likely this query didn't populate the fields of the WindowNode and so operator correctly. Let me double check.

**Comment by spershin** [comment] 2023-07-03 20:28
Thanks, @aditi-pandit !
I double-checked the RowContainer and reading vectors back from it is fine, so it is definitely something wrong in Window operator.
Thanks for looking into it!

**Comment by aditi-pandit** [comment] 2023-07-03 22:15
@spershin : Debugged this more. Presto always seems to use a column for k (even if its a constant). So the parsing was correct. Though what I noticed was that this column is always an INTEGER (and not a BIGINT as expected by the Windows code).

Please can you check the plan JSON and tell me if you observe the same. In any case, we should fix the Window operator code to allow INTEGER in those places.

**Comment by amitkdutta** [comment] 2023-07-07 19:32
@aditi-pandit It's easily reproducible locally with 1 coordinator and 1 worker, in every run

```
adutta@adutta-mbp target % java -jar presto-cli-0.283-SNAPSHOT-executable.jar --catalog hive --schema tpch
presto:tpch> SELECT b.ds, LAG(spend_this_period, 7) OVER ( ORDER BY b.ds ROWS BETWEEN 7 PRECEDING AND CURRENT ROW ) AS spend_prev_period FROM ( SELECT * FROM ( VALUES ( DATE('2023-06-21'), 95317.96574958303 ) ) AS a (ds, spend_this_period) ) a RIGHT JOIN ( SELECT * FROM ( VALUES ( DATE('2023-06-21') ), ( DATE('2023-06-22') ) ) AS r(ds) ) b ON b.ds = a.ds;

Query 20230707_193127_00007_kseie, FAILED, 1 node
Splits: 3 total, 0 done (0.00%)
[Latency: client-side: 101ms, server-side: 84ms] [0 rows, 0B] [0 rows/s, 0B/s]

Query 20230707_193127_00007_kseie failed: offsets[i] >= 1 (-1095216660473 vs. 1) k in frame bounds must be at least 1

presto:tpch> SELECT b.ds, LAG(spend_this_period, 7) OVER ( ORDER BY b.ds ROWS BETWEEN 7 PRECEDING AND CURRENT ROW ) AS spend_prev_period FROM ( SELECT * FROM ( VALUES ( DATE('2023-06-21'), 95317.96574958303 ) ) AS a (ds, spend_this_period) ) a RIGHT JOIN ( SELECT * FROM ( VALUES ( DATE('2023-06-21') ), ( DATE('2023-06-22') ) ) AS r(ds) ) b ON b.ds = a.ds;

Query 20230707_193129_00009_kseie, FAILED, 1 node
Splits: 3 total, 0 done (0.00%)
[Latency: client-side: 92ms, server-side: 82ms] [0 rows, 0B] [0 rows/s, 0B/s]

Query 20230707_193129_00009_kseie failed: offsets[i] >= 1 (-1095216660473 vs. 1) k in frame bounds must be at least 1
```

**Comment by aditi-pandit** [comment] 2023-07-07 19:55
@amitkdutta : Please can you send me the plan fragment json you see. 

I noticed some problem with the plan I generated, but since I wasn't able to see the reproduce the crash, I want to confirm with yours.

**Comment by amitkdutta** [comment] 2023-07-07 21:03
@aditi-pandit  here is the full json plan
[json_window_plan.txt](https://github.com/facebookincubator/velox/files/11986104/json_window_plan.txt)

**Comment by aditi-pandit** [comment] 2023-07-07 21:11
Thanks @amitkdutta. This reflects the problem I observed too. 

I'll send you a PR later in the evening (latest tomorrow morning) to verify.

**Comment by aditi-pandit** [comment] 2023-07-08 17:42
Fixed by https://github.com/facebookincubator/velox/pull/5570

**Closed** 2023-07-11 19:44 UTC
Labels: bug, triage
