### ISSUE TITLE
curl dependency build is showing many deprecated-declarations warnings on MacOS

### ISSUE THREAD

**Issue by majetideepak** [facebookincubator/velox#7881] opened 2023-12-05 14:04 UTC
### Problem description

cmake-build-debug/_deps/curl-src/lib/vtls/sectransp.c:3408:9: warning: 'SSLRead' is deprecated: first deprecated in macOS 10.15 - No longer supported. Use Network.framework. [-Wdeprecated-declarations]
  err = SSLRead(backend->ssl_ctx, buf, buffersize, &processed);
        ^
/Library/Developer/CommandLineTools/SDKs/MacOSX14.0.sdk/System/Library/Frameworks/Security.framework/Headers/SecureTransport.h:1689:1: note: 'SSLRead' has been explicitly marked deprecated here
SSLRead                                         (SSLContextRef          context,

64 warnings generated.

### System information

Velox System Info v0.0.2
Commit: 4bbd0f830c7f222087c4c3aca7818bc15794ce4b
CMake Version: 3.26.4
System: Darwin-22.6.0
Arch: arm64
C++ Compiler: /Library/Developer/CommandLineTools/usr/bin/c++
C++ Compiler Version: 15.0.0.15000040
C Compiler: /Library/Developer/CommandLineTools/usr/bin/cc
C Compiler Version: 15.0.0.15000040
CMake Prefix Path: /Library/Developer/CommandLineTools/SDKs/MacOSX14.0.sdk/usr;/opt/homebrew;/usr/local;/usr;/;/opt/homebrew/Cellar/cmake/3.26.4;/usr/local;/usr/X11R6;/usr/pkg;/opt;/sw;/opt/local

**Comment by majetideepak** [comment] 2023-12-05 14:04
CC @duanmeng

**Comment by duanmeng** [comment] 2023-12-05 15:16
@assignUser Hi Jacob, is this the problem you mentioned in https://github.com/facebookincubator/velox/pull/7853#issuecomment-1838637535?

**Comment by duanmeng** [comment] 2023-12-05 15:17
@majetideepak Could you try -DCPR_USE_SYSTEM_CURL=ON?

**Comment by assignUser** [comment] 2023-12-11 22:48
Duplicate of #7235

**Closed by assignUser** 2023-12-11 22:48 UTC
Labels: build, triage
