### ISSUE TITLE
FOLLY 2022.11.14.00 doesn't build on mac M1 laptop

### ISSUE THREAD

**Issue by guibin** [facebookincubator/velox#3453] opened 2022-12-08 19:16 UTC
### Problem description

When do 
` CPU_TARGET="arm64" make `
 it complains the below error:
```
-- Build files have been written to: /Users/guibin/velox/_build/debug
/Library/Developer/CommandLineTools/usr/bin/make build BUILD_DIR=debug -j 10
cmake --build _build/debug -j 10
[49/1275] Building CXX object _deps/folly-build/CMakeFiles/folly_base.dir/folly/detail/base64_detail/Base64_SSE4_2.cpp.o
FAILED: _deps/folly-build/CMakeFiles/folly_base.dir/folly/detail/base64_detail/Base64_SSE4_2.cpp.o
ccache /Library/Developer/CommandLineTools/usr/bin/c++ -DBOOST_ATOMIC_DYN_LINK -DBOOST_ATOMIC_NO_LIB -DBOOST_CONTEXT_DYN_LINK -DBOOST_CONTEXT_NO_LIB -DBOOST_FILESYSTEM_DYN_LINK -DBOOST_FILESYSTEM_NO_LIB -DBOOST_PROGRAM_OPTIONS_DYN_LINK -DBOOST_PROGRAM_OPTIONS_NO_LIB -DBOOST_REGEX_DYN_LINK -DBOOST_REGEX_NO_LIB -DBOOST_SYSTEM_DYN_LINK -DBOOST_SYSTEM_NO_LIB -DBOOST_THREAD_DYN_LINK -DBOOST_THREAD_NO_LIB -DFMT_LOCALE -DFOLLY_XLOG_STRIP_PREFIXES=\"/Users/guibin/velox:/Users/guibin/velox/_build/debug\" -DGFLAGS_IS_A_DLL=0 -D_GNU_SOURCE -D_REENTRANT -I/opt/homebrew/opt/icu4c/include -I/Users/guibin/velox/_build/debug/_deps/folly-src -I/Users/guibin/velox/_build/debug/_deps/folly-build -I/usr/local/include -I/Users/guibin/homebrew/opt/openssl@1.1/include -isystem /Users/guibin/homebrew/include -mcpu=apple-m1+crc -std=c++17 -fvisibility=hidden -D USE_VELOX_COMMON_BASE -D HAS_UNCAUGHT_EXCEPTIONS -Werror -Wall -Wextra -Wno-unused        -Wno-unused-parameter        -Wno-sign-compare        -Wno-ignored-qualifiers        -Wno-range-loop-analysis -Wno-mismatched-tags -g -g -Wall -Wextra -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX13.0.sdk -fPIC -g -std=gnu++1z -finput-charset=UTF-8 -fsigned-char -Wall -Wno-deprecated -Wno-deprecated-declarations -Wno-sign-compare -Wno-unused -Wuninitialized -Wunused-label -Wunused-result -Wno-overloaded-virtual -Wno-noexcept-type -Wno-nullability-completeness -Wno-inconsistent-missing-override -faligned-new -std=gnu++17 -msse4.2 -MD -MT _deps/folly-build/CMakeFiles/folly_base.dir/folly/detail/base64_detail/Base64_SSE4_2.cpp.o -MF _deps/folly-build/CMakeFiles/folly_base.dir/folly/detail/base64_detail/Base64_SSE4_2.cpp.o.d -o _deps/folly-build/CMakeFiles/folly_base.dir/folly/detail/base64_detail/Base64_SSE4_2.cpp.o -c /Users/guibin/velox/_build/debug/_deps/folly-src/folly/detail/base64_detail/Base64_SSE4_2.cpp
clang: error: argument unused during compilation: '-msse4.2' [-Werror,-Wunused-command-line-argument]
[58/1275] Building CXX object _deps/folly-build/CMakeFiles/folly_base.dir/folly/executors/CPUThreadPoolExecutor.cpp.o
ninja: build stopped: subcommand failed.
make[1]: *** [build] Error 1
make: *** [debug] Error 2
```
If reducing the version of Folloy to `v2022.07.11.00`, then the build works.

### System information

The scripts/info.sh doesn't work on mac M1 laptop
It complains `grep: invalid option -- P`

Here is info I manually got:
Velox System Info v0.0.1
Commit: c614ca4e0c2d2991ffaf102f58654d37c4f1babe
CMake Version:  3.25.1
System: mac os Ventura 13.0 (22A380)
Arch: Darwin guibin-mbp 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000 arm64
C++ Compiler: 
C++ Compiler Version: 
C Compiler: 
C Compiler Version: 
CMake Prefix Path: 

### CMake log

```bash
....
-- Build files have been written to: /Users/guibin/velox/_build/debug
/Library/Developer/CommandLineTools/usr/bin/make build BUILD_DIR=debug -j 10
cmake --build _build/debug -j 10
[49/1275] Building CXX object _deps/folly-build/CMakeFiles/folly_base.dir/folly/detail/base64_detail/Base64_SSE4_2.cpp.o
FAILED: _deps/folly-build/CMakeFiles/folly_base.dir/folly/detail/base64_detail/Base64_SSE4_2.cpp.o
ccache /Library/Developer/CommandLineTools/usr/bin/c++ -DBOOST_ATOMIC_DYN_LINK -DBOOST_ATOMIC_NO_LIB -DBOOST_CONTEXT_DYN_LINK -DBOOST_CONTEXT_NO_LIB -DBOOST_FILESYSTEM_DYN_LINK -DBOOST_FILESYSTEM_NO_LIB -DBOOST_PROGRAM_OPTIONS_DYN_LINK -DBOOST_PROGRAM_OPTIONS_NO_LIB -DBOOST_REGEX_DYN_LINK -DBOOST_REGEX_NO_LIB -DBOOST_SYSTEM_DYN_LINK -DBOOST_SYSTEM_NO_LIB -DBOOST_THREAD_DYN_LINK -DBOOST_THREAD_NO_LIB -DFMT_LOCALE -DFOLLY_XLOG_STRIP_PREFIXES=\"/Users/guibin/velox:/Users/guibin/velox/_build/debug\" -DGFLAGS_IS_A_DLL=0 -D_GNU_SOURCE -D_REENTRANT -I/opt/homebrew/opt/icu4c/include -I/Users/guibin/velox/_build/debug/_deps/folly-src -I/Users/guibin/velox/_build/debug/_deps/folly-build -I/usr/local/include -I/Users/guibin/homebrew/opt/openssl@1.1/include -isystem /Users/guibin/homebrew/include -mcpu=apple-m1+crc -std=c++17 -fvisibility=hidden -D USE_VELOX_COMMON_BASE -D HAS_UNCAUGHT_EXCEPTIONS -Werror -Wall -Wextra -Wno-unused        -Wno-unused-parameter        -Wno-sign-compare        -Wno-ignored-qualifiers        -Wno-range-loop-analysis -Wno-mismatched-tags -g -g -Wall -Wextra -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX13.0.sdk -fPIC -g -std=gnu++1z -finput-charset=UTF-8 -fsigned-char -Wall -Wno-deprecated -Wno-deprecated-declarations -Wno-sign-compare -Wno-unused -Wuninitialized -Wunused-label -Wunused-result -Wno-overloaded-virtual -Wno-noexcept-type -Wno-nullability-completeness -Wno-inconsistent-missing-override -faligned-new -std=gnu++17 -msse4.2 -MD -MT _deps/folly-build/CMakeFiles/folly_base.dir/folly/detail/base64_detail/Base64_SSE4_2.cpp.o -MF _deps/folly-build/CMakeFiles/folly_base.dir/folly/detail/base64_detail/Base64_SSE4_2.cpp.o.d -o _deps/folly-build/CMakeFiles/folly_base.dir/folly/detail/base64_detail/Base64_SSE4_2.cpp.o -c /Users/guibin/velox/_build/debug/_deps/folly-src/folly/detail/base64_detail/Base64_SSE4_2.cpp
clang: error: argument unused during compilation: '-msse4.2' [-Werror,-Wunused-command-line-argument]
[58/1275] Building CXX object _deps/folly-build/CMakeFiles/folly_base.dir/folly/executors/CPUThreadPoolExecutor.cpp.o
ninja: build stopped: subcommand failed.
make[1]: *** [build] Error 1
make: *** [debug] Error 2
```

**Comment by darrenfu** [comment] 2022-12-10 02:31
As Apple M1 users, you shouldn't see such a [`sse` compile flag](https://github.com/facebookincubator/velox/blob/main/scripts/setup-helper-functions.sh#L111), could you paste the output of the following commands?
```
uname
uname -m
sysctl -a | grep machdep.cpu
```

**Comment by isadikov** [comment] 2023-01-11 01:42
I have also encountered this issue and confirm that folly `v2022.07.11.00` works.

```
Velox System Info v0.0.2
Commit: bb2ecea223293eadb749936c37fec0d4ff3c89af
CMake Version: 3.25.1
System: Darwin-21.6.0
Arch: arm64
C++ Compiler: /Library/Developer/CommandLineTools/usr/bin/c++
C++ Compiler Version: 14.0.0.14000029
C Compiler: /Library/Developer/CommandLineTools/usr/bin/cc
C Compiler Version: 14.0.0.14000029
CMake Prefix Path: /Library/Developer/CommandLineTools/SDKs/MacOSX13.1.sdk/usr;/opt/homebrew;/usr/local;/usr;/;/opt/homebrew/Cellar/cmake/3.25.1;/usr/local;/usr/X11R6;/usr/pkg;/opt;/sw;/opt/local
```

uname
```
Darwin
```

uname -m
```
arm64
```

sysctl -a | grep machdep.cpu
```
machdep.cpu.cores_per_package: 10
machdep.cpu.core_count: 10
machdep.cpu.logical_per_package: 10
machdep.cpu.thread_count: 10
machdep.cpu.brand_string: Apple M1 Pro
```

@darrenfu Let me know if you need any other info to troubleshoot. I have also tested `v2023.01.09.00` - the same error.

**Comment by save-buffer** [comment] 2023-01-18 22:10
Hi, I am also on M1 and am getting the same thing. Same output for the commands you listed:
```
sasha:~/velox $ uname
uname -m
sysctl -a | grep machdep.cpu
Darwin
arm64
machdep.cpu.cores_per_package: 8
machdep.cpu.core_count: 8
machdep.cpu.logical_per_package: 8
machdep.cpu.thread_count: 8
machdep.cpu.brand_string: Apple M1
```

**Comment by fbalicchia** [comment] 2023-02-05 20:03
Hi I'm experiencing the same error too  
```
uname
uname -m
sysctl -a | grep machdep.cpu
Darwin
arm64
machdep.cpu.cores_per_package: 8
machdep.cpu.core_count: 8
machdep.cpu.logical_per_package: 8
machdep.cpu.thread_count: 8
machdep.cpu.brand_string: Apple M1
Darwin
arm64
machdep.cpu.cores_per_package: 8
machdep.cpu.core_count: 8
machdep.cpu.logical_per_package: 8
machdep.cpu.thread_count: 8
machdep.cpu.brand_string: Apple M1 Pro
```

**Comment by assignUser** [comment] 2023-03-02 03:07
This is caused by folly falsely assuming x86_64 if this is not set. https://github.com/facebook/folly/blob/main/CMakeLists.txt#L96-L99

I will open an issue there. Testing a fix in https://github.com/facebookincubator/velox/pull/4174

**Comment by assignUser** [comment] 2023-03-02 03:33
The fix worked so once that PR is merged building folly from source as part of velox will work again.

**Closed** 2023-03-03 20:49 UTC
Labels: build
