### ISSUE TITLE
Partial aggregations over distinct inputs are not supported.

### ISSUE THREAD

**Issue by hsshsssh** [facebookincubator/velox#8253] opened 2024-01-04 06:39 UTC
### Description

Partial aggregations over distinct inputs are not supported.

Partial aggregation must be supported for distributed execution of distinct aggregation. (for multiple drivers, multiple query execution engines).

Why is partial aggregation over distinct inputs not currently supported?

**Comment by mbasmanova** [comment] 2024-01-04 06:56
@hsshsssh Welcome to Velox community! Would you introduce yourself and share some context about your Velox related work and this particular question?

CC: @duanmeng

**Comment by hsshsssh** [comment] 2024-01-05 07:59
Sorry for any inconvenience caused by not providing detailed information earlier. 
Currently, we are building our in-house OLAP DB system using Velox, and we use a third-party tool for query planning. 
But, we have encountered an issue where the distinct count value is incorrectly calculated in queries that include count distinct.

We are trying to execute the following query:
select count(DISTINCT cs_order_number) as "order count" ,sum(cs_ext_ship_cost) as "total shipping cost" from catalog_sales;

The Velox plan generated through the plan we provide from our end is as follows.

 -- Project[expressions: (n5_2:BIGINT, ROW["n4_0"]), (n5_3:DECIMAL(38,2), ROW["n4_1"])] -> n5_2:BIGINT, n5_3:DECIMAL(38,2)
  -- Aggregation[FINAL n4_0 := count(ROW["n3_2"]), n4_1 := sum(ROW["n3_3"])] -> n4_0:BIGINT, n4_1:DECIMAL(38,2)
    -- Project[expressions: (n3_2:BIGINT, 1), (n3_3:VARBINARY, ROW["n2_1"])] -> n3_2:BIGINT, n3_3:VARBINARY
      -- Aggregation[PARTIAL [n1_2] n2_1 := sum(ROW["n1_3"])] -> n1_2:INTEGER, n2_1:VARBINARY
        -- Project[expressions: (n1_2:INTEGER, ROW["n0_0"]), (n1_3:DECIMAL(7,2), ROW["n0_1"])] -> n1_2:INTEGER, n1_3:DECIMAL(7,2)
          -- TableScan


There is an issue in the results of the Aggregation[PARTIAL] step, where duplicate keys persist for grouping keys, causing a problem of counting duplicated values. 
In investigating Velox's implementation for a solution, it appears that using a distinct flag within the Aggregate node's struct is a possible approach. 
However, the distinct flag does not support PartialOutput (Step::kPartial, Step::kIntermediate), especially when dealing with multiple max drivers.


The current version of Velox that we are using has the following commit ID and date. The latest commit does not provide support for this specific issue.

commit: 755e45ef849307d6aa3b4be197aa6d906afe14cb
Date: Thu Aug 03 2023 11:37:36 GMT+0900 (GMT+09:00)
 
We're wondering if Velox has any plans to help with partial results in distinct aggregation queries.
Alternatively, is there a way to use other aggregations along with count distinct in the current Velox version? 
Thanks a lot for all the help from the Velox community!

**Comment by mbasmanova** [comment] 2024-01-05 13:35
@hsshsssh Thank you for sharing this context. What's your name? How would you like us to refer to you? 

>  we are building our in-house OLAP DB system using Velox

Which company are you working for? What's the project name we can refer to?

> select count(DISTINCT cs_order_number) as "order count" ,sum(cs_ext_ship_cost) as "total shipping cost" from catalog_sales;

The query plan above is incorrect. There are a couple ways to plan this query.

(1) Using single aggregation (without splitting into partial and final).

(2) Using MarkDistinct with masked aggregation.

You can check query plans generated by Presto:

```
presto> set session use_mark_distinct=true;
presto> explain (type distributed) select count(distinct custkey), sum(totalprice) from tpch.tiny.orders;
                                                                                         Query Plan                                           >
---------------------------------------------------------------------------------------------------------------------------------------------->
 Fragment 0 [SINGLE]                                                                                                                          >
     Output layout: [count, sum]                                                                                                              >
     Output partitioning: SINGLE []                                                                                                           >
     - Output[PlanNodeId 8][_col0, _col1] => [count:bigint, sum:double]                                                                       >
             _col0 := count (1:35)                                                                                                            >
             _col1 := sum (1:60)                                                                                                              >
         - Aggregate(FINAL)[PlanNodeId 3] => [sum:double, count:bigint]                                                                       >
                 sum := "presto.default.sum"((sum_10)) (1:60)                                                                                 >
                 count := "presto.default.count"((count_11)) (1:35)                                                                           >
             - LocalExchange[PlanNodeId 256][SINGLE] () => [sum_10:double, count_11:bigint]                                                   >
                 - RemoteSource[1] => [sum_10:double, count_11:bigint]                                                                        >
                                                                                                                                              >
 Fragment 1 [HASH]                                                                                                                            >
     Output layout: [sum_10, count_11]                                                                                                        >
     Output partitioning: SINGLE []                                                                                                           >
     - Aggregate(PARTIAL)[PlanNodeId 260] => [sum_10:double, count_11:bigint]                                                                 >
             sum_10 := "presto.default.sum"((totalprice)) (1:60)                                                                              >
             count_11 := "presto.default.count"((custkey)) (mask = custkey_9) (1:35)                                                          >
         - MarkDistinct[PlanNodeId 49][distinct=custkey:bigint marker=custkey_9] => [custkey:bigint, totalprice:double, custkey_9:boolean]    >
             - LocalExchange[PlanNodeId 241][HASH] (custkey) => [custkey:bigint, totalprice:double]                                           >
                 - RemoteSource[2] => [custkey:bigint, totalprice:double]                                                                     >
                                                                                                                                              >
 Fragment 2 [tpch:orders:15000]                                                                                                               >
     Output layout: [custkey, totalprice]                                                                                                     >
     Output partitioning: HASH [custkey]                                                                                                      >
     - TableScan[PlanNodeId 0][TableHandle {connectorId='tpch', connectorHandle='orders:sf0.01', layout='Optional[orders:sf0.01]'}, grouped = >
             totalprice := tpch:totalprice (1:81)                                                                                             >
             custkey := tpch:custkey (1:81)                                                                                                   >
             tpch:orderstatus                                                                                                                 >
                 :: [["F"], ["O"], ["P"]]                                                                                                     >
                                                                                                                                              >
                                            

presto> set session use_mark_distinct=false;
presto> explain (type distributed) select count(distinct custkey), sum(totalprice) from tpch.tiny.orders;
                                                                                         Query Plan                                           >
---------------------------------------------------------------------------------------------------------------------------------------------->
 Fragment 0 [SINGLE]                                                                                                                          >
     Output layout: [count, sum]                                                                                                              >
     Output partitioning: SINGLE []                                                                                                           >
     - Output[PlanNodeId 8][_col0, _col1] => [count:bigint, sum:double]                                                                       >
             _col0 := count (1:35)                                                                                                            >
             _col1 := sum (1:60)                                                                                                              >
         - Aggregate[PlanNodeId 3] => [count:bigint, sum:double]                                                                              >
                 Estimates: {source: CostBasedSourceInfo, rows: 1 (18B), cpu: 540000.00, memory: 18.00, network: 270000.00}                   >
                 count := "presto.default.count"(DISTINCT (custkey)) (1:35)                                                                   >
                 sum := "presto.default.sum"((totalprice)) (1:60)                                                                             >
             - LocalExchange[PlanNodeId 180][SINGLE] () => [custkey:bigint, totalprice:double]                                                >
                 - RemoteSource[1] => [custkey:bigint, totalprice:double]                                                                     >
                                                                                                                                              >
 Fragment 1 [tpch:orders:15000]                                                                                                               >
     Output layout: [custkey, totalprice]                                                                                                     >
     Output partitioning: SINGLE []                                                                                                           >
     Stage Execution Strategy: UNGROUPED_EXECUTION                                                                                            >
     - TableScan[PlanNodeId 0][TableHandle {connectorId='tpch', connectorHandle='orders:sf0.01', layout='Optional[orders:sf0.01]'}, grouped = >
             totalprice := tpch:totalprice (1:81)                                                                                             >
             custkey := tpch:custkey (1:81)                                                                                                   >
             tpch:orderstatus                                                                                                                 >
                 :: [["F"], ["O"], ["P"]]                                                                                                     >
                                                                                                                                              >
                                                                                                                                              >
```

BTW, splitting aggregation over distinct values into partial and final is not really possible. You can see for yourself by trying to think though how to do that for a simple sum(distinct x).

If you are new to query plans and would like more detailed explanations, ping me on Slack and we can setup a VC.

**Comment by hsshsssh** [comment] 2024-01-08 01:21
Thank you for providing detailed explanations and Presto plans.

It would be good to refer to me as "hsshsssh".
We plan to integrate it as a component of our in-house product, and there are currently no publicly available projects.

Due to performance issues, we will not be using a single aggregation.
(2) MarkDistinct with masked aggregation looks like a good fit, and we'll give it a try.

Your detailed explanations have been very helpful, and I appreciate your assistance once again.

**Comment by duanmeng** [comment] 2024-01-08 06:43
An interesting article related to this topic https://www.qubole.com/blog/presto-optimizes-aggregations-over-distinct-values.

**Comment by hsshsssh** [comment] 2024-01-08 07:41
I have confirmed the use of grouping sets and aggregation in optimizing queries with multiple aggregations where one is aggregating on DISTINCT in an article.  Thank you for sharing the article as a reference!

**Comment by mbasmanova** [comment] 2024-01-08 14:12
@hsshsssh Sounds like the issue is resolved. I'm closing it, but feel free to reopen if you have any follow-up questions.

**Closed by mbasmanova** 2024-01-08 14:12 UTC
Labels: enhancement
