### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by natashaxin** [facebookincubator/velox#2948] opened 2022-10-25 04:18 UTC
CMake Error in velox/common/encode/CMakeLists.txt:
  Imported target "Folly::folly" includes non-existent path

    "/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/usr/include"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.

**Comment by zuochunwei** [comment] 2022-10-25 08:31
the directory of `/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk` does not exist, there is a directory of `/Library/Developer/CommandLineTools/SDKs/MacOSX11.1.sdk`.

why `Folly::folly` includes `/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/usr/include`, or how upgrade the MacOSX11.1.sdk to the new version of MacOSX12.sdk

**Comment by mbasmanova** [comment] 2022-10-25 13:00
CC: @kgpai @raulcd @Yuhta @pedroerp

**Comment by kgpai** [comment] 2022-10-28 05:56
Hi @natashaxin , Can you post the full cmake output so we can better debug ? Thanks.

**Comment by assignUser** [comment] 2023-01-18 01:12
Duplicate of #2924

**Closed by assignUser** 2023-01-18 01:12 UTC
Labels: build
