### ISSUE TITLE
Final avg for nulls on top of a row_constructor projection

### ISSUE THREAD

**Issue by rui-mo** [facebookincubator/velox#2385] opened 2022-08-25 13:45 UTC
Hi,
We found one issue on final avg for nulls with row_constructor.

As below, we are using final avg on top of a row_constructor projection.
```
.project({"c0", "row_constructor(c1, c2) as p0"})
.finalAggregation({"c0"}, {"avg(p0)"}, {DOUBLE()})
```
When the values of `c1` and `c2` are all null, the output of row_constructor projection (`p0`) does not reflect the validity information because its null buffer is set to nullptr (link: [RowFunction](https://github.com/facebookincubator/velox/blob/main/velox/functions/prestosql/RowFunction.cpp#L31-L37)).

```
RowVectorPtr row = std::make_shared<RowVector>(
        context->pool(),
        outputType,
        BufferPtr(nullptr),
        rows.size(),
        std::move(argsCopy),
        0 /*nullCount*/);
```
But in Average calculation, only the row vector is checked for `mayHaveNulls()` ([AverageAggregate](https://github.com/facebookincubator/velox/blob/main/velox/functions/prestosql/aggregates/AverageAggregate.cpp#L155-L195)). In this case, if the sum vector contains nulls, they are treated to be valid. `updateNonNullValue` will access the null value, which is invalid in fact, and try to calculate the final avg result. Therefore, we got strange result in this case.

Thanks.

**Comment by rui-mo** [comment] 2022-08-25 13:47
Try to fix this issue in https://github.com/facebookincubator/velox/pull/2386.

**Comment by mbasmanova** [comment] 2022-08-25 13:57
> If the values of one column are all nulls, Velox partial avg yields null for sum and null for count. But the duckdb result is null for sum and 0 for count.
This difference does not affect the result of final avg actually. Do you think they needed to aligned?

I don't see a reason for partial results to match DuckDB.

**Comment by mbasmanova** [comment] 2022-08-25 14:00
> As below, we are using final avg on top of a row_constructor projection.

I think the problem is in how the application is unpacking and re-assembling partial results. I assume partial agg returns a row vector with some entries being null. The application then unpacks it into two null scalars (count and sum). This transformation looses some information, specifically a null flag in the original row. Hence, combining the count and sum back doesn't work correctly. I suggest to unpack the row into 3 columns: count, sum, is_null. Then, assemble back using

`if (is_null, null, row_constructor(count, sum)`

**Comment by rui-mo** [comment] 2022-08-25 15:13
Hi Masha, thanks for your suggestion.
> I suggest to unpack the row into 3 columns: count, sum, is_null. 

Looks like if we extract an extra column for is_null, the batch could be uncompatible with our current shuffle code. Because the input and output fields in shuffle are already decided by Spark, we may need to replan it in this case.
If we still unpack it into count and sum, and assemblle back using `if (sum is null, null, row_constructor(count, sum))`, looks like an extra check for the validity of `sum` is needed.

**Comment by mbasmanova** [comment] 2022-08-25 15:22
@rui-mo Would you share the input data and query that produces the wrong result? I assume the query is SELECT a, avg(b) FROM t, but what are the values for 'a' and 'b'?

**Comment by rui-mo** [comment] 2022-08-25 15:33
> Would you share the input data and query that produces the wrong result?

This issue only happens when the input of final avg is the assembled row vector of sum and count using `row_constructor`. I think It could be reproduced with below test. Most values in the  sum column are set to null.

```
TEST_F(AverageAggregationTest, finalAvgForNullsWithRowConstructor) {
  auto batchSize = 1'000;
  auto rowType = ROW({"c0", "c1", "c2"}, {INTEGER(), DOUBLE(), BIGINT()});

  auto sumVec = makeFlatVector<double>(batchSize, [](auto row) { return row; });
  for (auto i = 0; i < sumVec->size() - 1; i++) {
    // One value is not null to avoid constant mapping.
    sumVec->setNull(i, true);
  }
  auto countVec =
      makeFlatVector<int64_t>(batchSize, [](auto row) { return 0; });

  auto data = makeRowVector(
      {makeFlatVector<int32_t>(
           batchSize, [](auto row) { return row % 100; }, nullEvery(6)),
       sumVec,
       countVec});
  createDuckDbTable({data});

  auto planNode = PlanBuilder()
                      .values({data})
                      .project({"c0", "row_constructor(c1, c2) as p0"})
                      .finalAggregation({"c0"}, {"avg(p0)"}, {DOUBLE()})
                      .planNode();

  assertQuery(planNode, "SELECT c0, sum(c1) / count(c2) FROM tmp group by c0");
}
```

**Comment by mbasmanova** [comment] 2022-08-25 15:53
@rui-mo Rui, thank you for clarifying. It sounds like the problem happens only if input to final aggregation is different from the output of the partial aggregation. If that's the case, could you adjust the logic between partial and final aggregation to ensure the partial results are not modified?

**Comment by rui-mo** [comment] 2022-08-26 02:03
> It sounds like the problem happens only if input to final aggregation is different from the output of the partial aggregation.

Yes, they are different in our use case. The output of partial avg is separated into sum and count for shuffle. Sum and count are then assembled back for final avg. This is our current logic.
```
=> partial_avg(c0) --> row(sum, count) as partial_output
=> project({"partial_output.sum", "partial_output.count"})
=> velox to arrow
=> shuffle for arrow data
=> arrow to velox (arrow stream node)
=> project("{row_constructor("partial_output.sum", "partial_output.count") as p0}")
=> final_avg(p0)
```

**Comment by mbasmanova** [comment] 2022-08-29 16:55
@rui-mo Rui, thank you for explaining. It seem that we need a different solution which would preserve the null-ness of the intermediate results. Have you looked into a possibility of changing the Spark query plan? We have introduced a change to Presto that allows to override the intermediate result types for aggregation functions. Perhaps, something similar can be done in Spark.

**Comment by rui-mo** [comment] 2022-09-01 01:46
> It seem that we need a different solution which would preserve the null-ness of the intermediate results. Have you looked into a possibility of changing the Spark query plan? We have introduced a change to Presto that allows to override the intermediate result types for aggregation functions. Perhaps, something similar can be done in Spark.

@mbasmanova Masha, thank you for the helpful suggestion. We agree we should change the Spark query plan to support struct as the intermediate type of aggregation. But it still takes some time for us to support struct type in our columnar shuffle. Before that completes, we plan to specially handle this case to make the query result correct. Do you think that makes sense? Maybe we can close this issue for now.
cc @FelixYBW

**Comment by mbasmanova** [comment] 2022-09-01 14:57
@rui-mo Sounds good to me.

> we plan to specially handle this case to make the query result correct

Do you have a way to special case this some how in Gluten? Curious, how that trick works.

> Maybe we can close this issue for now.

Let's close.

**Comment by rui-mo** [comment] 2022-09-02 07:50
> Do you have a way to special case this some how in Gluten? Curious, how that trick works.

For the temporary solution, currently just like the PR shows, we extraly check the validity of the `sum` vector in Velox.  In this way, the nulls will not be accessed.

**Comment by mbasmanova** [comment] 2022-09-06 13:59
@rui-mo Rui, thank you for clarifying. Closing the PR as discussed above.

**Closed by mbasmanova** 2022-09-06 13:59 UTC
Labels: bug
